### ISSUE TITLE
一个不相关的问题。回复完我删掉。

### ISSUE THREAD

**Issue by yqjiang** [jackyyf/bilidanmaku#1]
昨天给郑谦发的问题看到了。当时为了兼容FLVJS cancel的时候没有await那个promise、 后来结束AB test以后，播放器外层介入了新的程序员在写，不可能面面聚到。当时我也不记得那边有个问题。没有说，没改造成的。现在应该不会再发生。

panda-mccree 内核unload
return new Promise(function (resolve, reject) {
……
that._reader.cancel().then(function () {
	            that.loading = false;
	            resolve();
	          });
});

flvjs unload
return reader.cancel();

其实这个问题 A/Btest 时候一直有。也被反馈了不少次了。
但是如果等这个异步，流错误切回flash在flvjs 的情况下就会切不回去 

以及。以后有问题。烦请直接向我反馈或者直接熊猫的H5群。AT群主。现在属于我这边在维护的（前端项目）panda-mccree / panda-danmaku 这两个项目问题，直接邮件我即可，gayhub有。如果没看见，麻烦等等。 毕竟不是客服，平时还要写代码。

祝好。

**Comment by jackyyf** [comment]
Hi,

十分抱歉昨天我的部分群内的话语给您造成了困扰，事后仔细想想觉得还是有些不妥，在此向您表示歉意。我的初衷是因为斗鱼HTML5播放器的维护者也在那个群里，同时斗鱼HTML5播放器也有类似问题，所以在群里吐槽了一下，没有注意语气，在此再次向您表示抱歉。

由于我日常工作系统是Debian 9，不太方便使用QQ等IM，所以见到了bug也不太方便向QQ群内反馈，感谢您提到了邮件途径，以后我遇到了类似的问题会通过邮件或Github Issue途径向您汇报 :)

由于我在学校时学校的国内出口十分拥挤但是IPv6到国外的出口十分空闲，故我经常使用国外线路看视频和直播，链路质量不是太稳定，更容易触发这个bug，感谢您修复了这个bug :)

**Comment by yqjiang** [comment]
可以和斗鱼的同学说，在flvjs的fetch stream 中修正 Cancel 由于其他几个loader也同样方式调用。建议统一
 return new Promise 的方式。cancel 和load都是。外层在调用的时候，会比较好处理。

熊猫的内核，我还在争取开源的事情。不过应该是在对CDN-union所提到的新协议做了支持之后，尚在进行中。如果对协议有什么意见和建议 欢迎向CDN-union提出 (ˇˍˇ) https://github.com/CDN-Union/

谢谢支持 。
